name: Maven Tests CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, review_requested, edited]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run Tests with Maven
        run: mvn test